### ISSUE TITLE
wait for code

### ISSUE THREAD

**Issue by 3462994500** [UNIC-Lab/Qedgix#1]

**Comment by yikuanglancheng** [comment]
The code is released.

**Comment by 3462994500** [comment]
Thanks.
But I meet problem.
ModuleNotFoundError: No module named 'pymarl.modules.agents.ff_agent'
Qedgix-main\pymarl\modules\agents lost two files: ff_agent.py and atten_rnn_agent.py

**Comment by yikuanglancheng** [comment]
These two modules are never used, you can just delete them. Moreover, we update the pymarl.zip for that
