### ISSUE TITLE
Missing environment implementation

### ISSUE THREAD

**Issue by DoudouMee** [UNIC-Lab/Qedgix#3]
It seems the environment `uav` in the paper is missing
  File "E:\PyCharmPRJ\Qedgix-main\pymarl\envs\__init__.py", line 14, in <module>
    from .uav import UAVEnv
ModuleNotFoundError: No module named 'pymarl.envs.uav'

**Comment by yikuanglancheng** [comment]
Since the environment file needs to be used in another paper being written, it is not provided. The Repo only provides algorithm-related files.
